# Generated by Django 3.0.5 on 2020-04-25 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='point',
            new_name='point_recieved',
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='total_point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
