# Generated by Django 3.0.5 on 2020-04-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='SKMCH&RC |', max_length=200),
        ),
    ]
