# Generated by Django 3.0.5 on 2020-04-25 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20200426_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='point',
            new_name='rating',
        ),
    ]
