# Generated by Django 3.0.5 on 2020-04-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20200429_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='grade',
            new_name='scale',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='title',
        ),
    ]
