# Generated by Django 3.0.5 on 2020-04-30 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20200430_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='children',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cnic',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(default='Safety & Security Department', max_length=60),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='father_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gross_salary',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30000000)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='home_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_1',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_main',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='scale',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='employee',
            name='spouse_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
