# Generated by Django 3.0.5 on 2020-04-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20200430_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cnic',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='employee',
            name='home_phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_1',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_2',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_main',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='employee',
            name='spouse_phone',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
