# Generated by Django 3.0.5 on 2020-05-29 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20200529_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.date(2020, 5, 29)),
        ),
    ]
