# Generated by Django 3.0.5 on 2020-04-26 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20200426_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='point_recieved',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
