# Generated by Django 3.0.5 on 2020-04-23 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_code', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_main', models.CharField(max_length=200)),
                ('phone_1', models.CharField(blank=True, max_length=200)),
                ('phone_2', models.CharField(blank=True, max_length=200)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_available', models.BooleanField(default=True)),
                ('salary', models.IntegerField()),
                ('join_date', models.DateTimeField(default=datetime.datetime.now)),
                ('listing_date', models.DateTimeField(default=datetime.datetime.now)),
                ('jd', models.TextField(blank=True)),
                ('designation', models.CharField(max_length=200)),
                ('department', models.CharField(default='Safety & Security Department', max_length=200)),
            ],
        ),
    ]
