# Generated by Django 3.0.5 on 2020-04-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
